#!/usr/bin/env python3
"""
Stress test for prism's redirect handler (GET /{path:*} → 301/404).

Orchestrates:
  1. prism built with -tags debug (pprof enabled)
  2. A test config.yaml with populated URL trie (dummy backends)
  3. Concurrent HTTP load against catch-all redirect paths
  4. Metrics collection (latency percentiles, throughput, errors)
  5. Clean shutdown + pprof file collection

Unlike stress-mirrors.py, this test needs NO mock services — the redirect
handler only uses the path resolver (trie) and the web handler (for 404s).
The trie is populated from config at startup.  The mirror manager and index
provider are initialized with unreachable endpoints and never called by the
redirect code path.

Usage:
  python3 test/stress-redirect/stress-redirect.py [--interval 30] [--concurrency 10]
"""

import argparse
import concurrent.futures
import datetime
import itertools
import json
import pathlib
import random
import shutil
import signal
import statistics
import subprocess
import sys
import tempfile
import textwrap
import threading
import time
import urllib.request
from typing import Optional

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
PRISM_SOURCE = PROJECT_ROOT / "cmd" / "prism"

DEFAULT_PRISM_LISTEN = "127.0.0.1:8081"
DEFAULT_PRISM_PORT = 8081
DEFAULT_INTERVAL = 30
DEFAULT_CONCURRENCY = 10
DEFAULT_VALID_RATIO = 0.8  # Fraction of requests that hit a valid prefix (→301)
DEFAULT_PATH_COUNT = 200   # Number of unique paths to generate

# ---------------------------------------------------------------------------
# Mirror names used in config.  Each host gets a distinct subset so the trie
# is populated with realistic prefix density.
# ---------------------------------------------------------------------------

MOCK_MIRRORS_HOST1 = [
    ("alpine", "Alpine Linux"),
    ("archlinux", "Arch Linux"),
    ("centos", "CentOS"),
    ("debian", "Debian"),
    ("fedora", "Fedora"),
    ("gentoo-portage", "Gentoo Portage"),
    ("gnu", "GNU"),
    ("manjaro", "Manjaro"),
    ("openwrt", "OpenWrt"),
    ("ubuntu", "Ubuntu"),
]

MOCK_MIRRORS_HOST2 = [
    ("centos-vault", "CentOS Vault"),
    ("deepin", "deepin"),
    ("epel", "EPEL"),
    ("kali-images", "Kali Images"),
    ("raspbian", "Raspbian"),
    ("rocky", "Rocky Linux"),
    ("ros", "ROS"),
    ("ros2", "ROS 2"),
    ("ubuntu-ports", "Ubuntu Ports"),
    ("vim", "Vim"),
]

# Collect valid URL prefixes for path generation.  Must match url_prefix
# values generated by _mirrors_yaml below (i.e. "/host1/alpine/", etc.).
ALL_VALID_PREFIXES = (
    [f"/host1/{name}/" for name, _ in MOCK_MIRRORS_HOST1]
    + [f"/host2/{name}/" for name, _ in MOCK_MIRRORS_HOST2]
)


def _mirrors_yaml(mirrors: list[tuple[str, str]], url_prefix_base: str) -> str:
    """Generate YAML lines for a list of (name, desc) mirror entries.

    Returns content with 0 base-indent so it can be indented uniformly by
    the caller via ``textwrap.indent``.
    """
    lines = []
    for name, desc in mirrors:
        lines.append(
            f"- name: {name}\n"
            f'  desc: "{desc}"\n'
            f"  type: rsync\n"
            f"  url_prefix: {url_prefix_base}/{name}/\n"
            f"  real_url_prefix: {url_prefix_base}/{name}/\n"
            f"  help:\n"
            f'    mode: "off"'
        )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def http_get_no_redirect(url: str, timeout: float = 5.0) -> tuple[int, float]:
    """Perform an HTTP GET **without following redirects**.

    Returns (status_code, elapsed_seconds).  This is critical for the
    redirect stress test because the redirect target (host FQDN) points to
    an unreachable address (127.0.0.1 with no server on port 80).  Following
    the 301 would always result in a connection error instead of measuring
    the redirect latency.
    """
    start = time.monotonic()

    class NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, req, fp, code, msg, headers, newurl):
            return None

    opener = urllib.request.build_opener(NoRedirect())
    try:
        with opener.open(url, timeout=timeout) as resp:
            _ = resp.read()
            return resp.status, time.monotonic() - start
    except urllib.error.HTTPError as e:
        # e.code is set when the server returns a response; for 301/404 we
        # still get here because the NoRedirect handler doesn't redirect.
        return e.code, time.monotonic() - start
    except Exception:
        return 0, time.monotonic() - start


def health_check(
    url: str,
    timeout: float = 2.0,
    retries: int = 30,
    interval: float = 0.5,
) -> bool:
    """Poll a URL until it responds 200 or retries exhausted."""
    for _ in range(retries):
        try:
            with urllib.request.urlopen(url, timeout=timeout) as resp:
                if resp.status == 200:
                    return True
        except Exception:
            pass
        time.sleep(interval)
    return False


def kill_process(proc: subprocess.Popen, name: str) -> None:
    """Gracefully terminate a process, then force-kill if needed."""
    if proc is None or proc.poll() is not None:
        return
    print(f"  Stopping {name} (pid={proc.pid})...")
    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        print(f"  Force-killing {name}...")
        proc.kill()
        proc.wait()


def timestamp() -> str:
    """Return a compact ISO-8601 timestamp for directory naming."""
    return datetime.datetime.now().strftime("%Y%m%dT%H%M%S")


# ---------------------------------------------------------------------------
# Path generation
# ---------------------------------------------------------------------------


def rand_subpath(rng: random.Random, depth: int = 0) -> str:
    """Generate a random sub-path segment to append after a prefix."""
    import string

    if depth <= 0:
        depth = rng.randint(1, 4)
    parts = []
    for _ in range(depth):
        length = rng.randint(3, 12)
        segment = "".join(rng.choices(string.ascii_lowercase + string.digits, k=length))
        parts.append(segment)
    return "/".join(parts) + "/"


def rand_invalid_path(rng: random.Random) -> str:
    """Generate a path that is guaranteed NOT to match any registered prefix."""
    import string

    # Use prefixes that look like real ones but aren't in our mirror list.
    bogus = rng.choice([
        "random", "nonexistent", "fake", "invalid", "bogus",
        "testdata", "experimental", "staging", "legacy", "custom",
    ])
    length = rng.randint(3, 12)
    sub = "".join(rng.choices(string.ascii_lowercase + string.digits, k=length))
    return f"/{bogus}/{sub}/"


def generate_paths(
    valid_prefixes: list[str],
    valid_count: int,
    invalid_count: int,
    seed: int = 42,
) -> list[str]:
    """Generate a reproducible list of paths.

    *valid_count* paths start with a known prefix (→ 301 redirect expected).
    *invalid_count* paths do not match any prefix (→ 404 expected).
    """
    rng = random.Random(seed)
    paths: list[str] = []

    for _ in range(valid_count):
        prefix = rng.choice(valid_prefixes)
        sub = rand_subpath(rng)
        paths.append(prefix + sub)

    for _ in range(invalid_count):
        paths.append(rand_invalid_path(rng))

    rng.shuffle(paths)
    return paths


# ---------------------------------------------------------------------------
# Config generation
# ---------------------------------------------------------------------------


def build_test_config() -> str:
    """Generate a test config.yaml as a string.

    The config has two hosts with 10 mirrors each, populating the URL trie
    with 20 prefixes.  tunasync and nginx endpoints point at an unreachable
    port — neither subsystem is used by the redirect handler.
    """
    template = textwrap.dedent("""\
    log:
      level: warn
      output: stderr

    access_log:
      level: error
      output: stderr

    http:
      listen: "{prism_listen}"
      proto_header: "X-Forwarded-Proto"
      tcp_keepalive: true

    index:
      cache_ttl: 5m
      cache_max_bytes: 64MB

    sync_status:
      cache_ttl: 60s
      fetch_timeout: 1s

    hosts:
    - name: host1
      fqdn: 127.0.0.1
      index:
        driver: nginx
        nginx:
          timeout: 1s
          base_url: http://127.0.0.1:1/api/index/
      sync_status:
        driver: tunasync
        ttl: 60s
        tunasync:
          endpoint: http://127.0.0.1:1/tunasync.json
          timeout: 1s
      mirrors:
    __HOST1_MIRRORS__
    - name: host2
      fqdn: 127.0.0.1
      index:
        driver: nginx
        nginx:
          timeout: 1s
          base_url: http://127.0.0.1:1/api/index/
      sync_status:
        driver: tunasync
        ttl: 60s
        tunasync:
          endpoint: http://127.0.0.1:1/tunasync.json
          timeout: 1s
      mirrors:
    __HOST2_MIRRORS__
    """)

    template = template.replace("{prism_listen}", DEFAULT_PRISM_LISTEN)

    # After dedent, ``mirrors:`` sits at 2-space indent under the host
    # block.  Mirror list items need 4-space indent (2 more).
    host1 = textwrap.indent(
        _mirrors_yaml(MOCK_MIRRORS_HOST1, "/host1"), "    "
    )
    host2 = textwrap.indent(
        _mirrors_yaml(MOCK_MIRRORS_HOST2, "/host2"), "    "
    )
    return template.replace("__HOST1_MIRRORS__", host1).replace(
        "__HOST2_MIRRORS__", host2
    )


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------


class MetricsCollector:
    """Thread-safe metrics aggregator."""

    def __init__(self):
        self._lock = threading.Lock()
        self.latencies: list[float] = []
        self.status_counts: dict[int, int] = {}
        self.total_requests = 0
        self.errors = 0  # non-2xx or connection errors

    def record(self, status: int, latency: float) -> None:
        with self._lock:
            self.total_requests += 1
            self.latencies.append(latency)
            self.status_counts[status] = self.status_counts.get(status, 0) + 1
            # For the redirect handler, both 301 and 404 are expected/normal.
            # Only connection errors (status 0) are actual errors.
            if status == 0:
                self.errors += 1

    def snapshot(self) -> dict:
        with self._lock:
            total = self.total_requests
            if total == 0:
                return {"total_requests": 0}

            lats = sorted(self.latencies)
            p50_idx = int(len(lats) * 0.50)
            p95_idx = int(len(lats) * 0.95)
            p99_idx = int(len(lats) * 0.99)

            return {
                "total_requests": total,
                "errors": self.errors,
                "error_rate": self.errors / total if total else 0,
                "status_counts": dict(self.status_counts),
                "latency": {
                    "min_ms": round(lats[0] * 1000, 3),
                    "max_ms": round(lats[-1] * 1000, 3),
                    "mean_ms": round(statistics.mean(lats) * 1000, 3),
                    "p50_ms": round(lats[min(p50_idx, len(lats) - 1)] * 1000, 3),
                    "p95_ms": round(lats[min(p95_idx, len(lats) - 1)] * 1000, 3),
                    "p99_ms": round(lats[min(p99_idx, len(lats) - 1)] * 1000, 3),
                },
            }


# ---------------------------------------------------------------------------
# Stress runner
# ---------------------------------------------------------------------------


class StressRunner:
    """Manages the full stress-test lifecycle."""

    def __init__(
        self,
        interval: int,
        concurrency: int,
        prism_port: int,
        output_dir: pathlib.Path,
        valid_ratio: float,
        path_count: int,
    ):
        self.interval = interval
        self.concurrency = concurrency
        self.prism_port = prism_port
        self.prism_listen = f"127.0.0.1:{prism_port}"
        self.output_dir = output_dir
        self.valid_ratio = valid_ratio
        self.path_count = path_count

        self._prism: Optional[subprocess.Popen] = None
        self._tmpdir: Optional[pathlib.Path] = None
        self._stop_event = threading.Event()
        self._metrics = MetricsCollector()

    # -- Process management --------------------------------------------------

    def _build_prism(self) -> pathlib.Path:
        """Build prism with debug tags, return binary path."""
        binary = self.output_dir / "prism-debug"
        print(f"Building prism (debug) -> {binary}...")
        subprocess.run(
            ["go", "build", "-tags", "debug", "-o", str(binary), "./cmd/prism/"],
            cwd=str(PROJECT_ROOT),
            check=True,
        )
        return binary

    def _start_prism(self, binary: pathlib.Path) -> subprocess.Popen:
        assert self._tmpdir is not None
        config_path = self._tmpdir / "config.yaml"
        config_path.write_text(self._config_yaml)
        proc = subprocess.Popen(
            [str(binary), "run", "--config", str(config_path)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            cwd=str(self._tmpdir),
        )
        print(f"  Started prism on {self.prism_listen} (pid={proc.pid})")
        return proc

    # -- Setup / teardown ----------------------------------------------------

    def setup(self) -> None:
        """Build binary, write config, start prism."""
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Build prism with debug tags
        prism_binary = self._build_prism()

        # Generate test config
        self._config_yaml = build_test_config()

        # Temp directory for prism's working dir (where pprof files land)
        self._tmpdir = pathlib.Path(
            tempfile.mkdtemp(prefix="prism-stress-")
        )

        # Start prism
        print("Starting prism (no mock services needed)...")
        self._prism = self._start_prism(prism_binary)

        # Health-check prism
        if not health_check(f"http://{self.prism_listen}/api/ping"):
            raise RuntimeError("prism failed to start")
        print("  Prism healthy.")

        # Warm up: hit a valid redirect path so we know the trie is loaded
        print("  Warming redirect handler (GET /host1/ubuntu/)...")
        status, elapsed = http_get_no_redirect(
            f"http://{self.prism_listen}/host1/ubuntu/", timeout=5.0
        )
        if status != 301:
            raise RuntimeError(
                f"prism redirect warm-up returned {status}, expected 301"
            )
        print(f"  Redirect warm-up OK ({elapsed*1000:.1f}ms)")

    def teardown(self, collect_profiles: bool = True) -> None:
        """Stop prism gracefully."""
        print("\nShutting down...")

        # Stop prism (SIGINT triggers deferred pprof writes)
        kill_process(self._prism, "prism")
        self._prism = None

        # Collect pprof files after prism has exited and flushed buffers
        if collect_profiles:
            self._collect_pprof()

        if self._tmpdir:
            shutil.rmtree(self._tmpdir, ignore_errors=True)
            self._tmpdir = None

    # -- Stress test ---------------------------------------------------------

    def _worker(self, paths_cycle: itertools.cycle) -> None:
        """Worker thread: hit redirect paths in a loop until stopped."""
        base_url = f"http://{self.prism_listen}"
        while not self._stop_event.is_set():
            path = next(paths_cycle)
            url = base_url + path
            status, latency = http_get_no_redirect(url)
            self._metrics.record(status, latency)

    def run(self) -> dict:
        """Run the stress test and return metrics snapshot."""
        # Generate paths
        valid_count = int(self.path_count * self.valid_ratio)
        invalid_count = self.path_count - valid_count or 1
        paths = generate_paths(
            ALL_VALID_PREFIXES, valid_count, invalid_count
        )
        print(
            f"Using {len(paths)} unique paths "
            f"({valid_count} valid → 301, {invalid_count} invalid → 404)"
        )
        paths_cycle = itertools.cycle(paths)

        print(
            f"\nStarting stress test: {self.interval}s, "
            f"{self.concurrency} workers"
        )
        print(f"Target: http://{self.prism_listen}/<random-path>\n")

        start_time = time.monotonic()

        with concurrent.futures.ThreadPoolExecutor(
            max_workers=self.concurrency
        ) as executor:
            futures = [
                executor.submit(self._worker, paths_cycle)
                for _ in range(self.concurrency)
            ]

            # Progress reporting
            try:
                last_reported = start_time
                while (elapsed := time.monotonic() - start_time) < self.interval:
                    time.sleep(1)
                    if time.monotonic() - last_reported >= 5:
                        snap = self._metrics.snapshot()
                        rate = (
                            snap["total_requests"] / elapsed
                            if elapsed > 0
                            else 0
                        )
                        print(
                            f"  [{elapsed:.0f}s] {snap['total_requests']} req, "
                            f"{rate:.1f} req/s, {snap['errors']} err"
                        )
                        last_reported = time.monotonic()
            except KeyboardInterrupt:
                print("\n  Interrupted — stopping workers...")

            self._stop_event.set()

            # Wait for all workers to finish
            concurrent.futures.wait(futures, timeout=10)

        elapsed = time.monotonic() - start_time
        metrics = self._metrics.snapshot()
        metrics["duration_sec"] = round(elapsed, 2)
        metrics["throughput_req_per_sec"] = round(
            metrics["total_requests"] / elapsed, 1
        ) if elapsed > 0 else 0
        metrics["concurrency"] = self.concurrency
        metrics["valid_ratio"] = self.valid_ratio
        metrics["path_count"] = self.path_count

        return metrics

    # -- Report --------------------------------------------------------------

    def report(self, metrics: dict) -> None:
        """Print a summary and write full JSON report."""
        print("\n" + "=" * 60)
        print("STRESS TEST RESULTS — handleRedirect")
        print("=" * 60)

        if metrics["total_requests"] == 0:
            print("  No requests completed.")
            return

        print(f"  Duration:           {metrics['duration_sec']}s")
        print(f"  Concurrency:        {metrics['concurrency']}")
        print(f"  Valid ratio:        {metrics['valid_ratio']:.0%}")
        print(f"  Total requests:     {metrics['total_requests']}")
        print(
            f"  Throughput:         {metrics['throughput_req_per_sec']} req/s"
        )
        print(
            f"  Errors:             {metrics['errors']} "
            f"({metrics['error_rate']*100:.2f}%)"
        )
        print()
        print("  Status distribution:")
        for code, count in sorted(metrics["status_counts"].items()):
            if code == 0:
                label = "connection error"
            elif code == 301:
                label = "HTTP 301 (redirect)"
            elif code == 404:
                label = "HTTP 404 (not found)"
            else:
                label = f"HTTP {code}"
            print(f"    {label:>24s}: {count}")

        lat = metrics["latency"]
        print()
        print("  Latency (ms):")
        print(f"    min: {lat['min_ms']:>10.3f}")
        print(f"    max: {lat['max_ms']:>10.3f}")
        print(f"    mean:{lat['mean_ms']:>10.3f}")
        print(f"    p50: {lat['p50_ms']:>10.3f}")
        print(f"    p95: {lat['p95_ms']:>10.3f}")
        print(f"    p99: {lat['p99_ms']:>10.3f}")

        print("=" * 60)

        # Write JSON report
        report_path = self.output_dir / "report.json"
        report_path.write_text(json.dumps(metrics, indent=2))
        print(f"\nFull report: {report_path}")

    # -- Pprof collection ----------------------------------------------------

    def _collect_pprof(self) -> None:
        """Copy pprof files from the temp working directory to output.

        Must be called AFTER prism has exited (so deferred writes have flushed).
        """
        if not self._tmpdir:
            return
        for pattern in ["*.pprof"]:
            for f in self._tmpdir.glob(pattern):
                dest = self.output_dir / f.name
                shutil.copy2(f, dest)
                size = dest.stat().st_size
                print(f"  Collected profile: {dest} ({size} bytes)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    ts = timestamp()

    parser = argparse.ArgumentParser(
        description="Stress test prism's redirect handler (GET /{path:*})",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              %(prog)s --interval 30 --concurrency 10
              %(prog)s --interval 60 --concurrency 50
              %(prog)s --interval 10 --concurrency 4 --output-dir ./results
              %(prog)s --interval 30 --concurrency 20 --valid-ratio 0.5
        """),
    )
    parser.add_argument(
        "--interval", "-t",
        type=int,
        default=DEFAULT_INTERVAL,
        help=f"Stress test duration in seconds (default: {DEFAULT_INTERVAL})",
    )
    parser.add_argument(
        "--concurrency", "-c",
        type=int,
        default=DEFAULT_CONCURRENCY,
        help=f"Number of concurrent workers (default: {DEFAULT_CONCURRENCY})",
    )
    parser.add_argument(
        "--prism-port",
        type=int,
        default=DEFAULT_PRISM_PORT,
        help=f"Port for prism (default: {DEFAULT_PRISM_PORT})",
    )
    parser.add_argument(
        "--valid-ratio", "-r",
        type=float,
        default=DEFAULT_VALID_RATIO,
        help=f"Fraction of paths that match a known prefix → 301 "
             f"(default: {DEFAULT_VALID_RATIO})",
    )
    parser.add_argument(
        "--path-count", "-n",
        type=int,
        default=DEFAULT_PATH_COUNT,
        help=f"Number of unique paths to generate (default: {DEFAULT_PATH_COUNT})",
    )
    parser.add_argument(
        "--output-dir", "-o",
        type=pathlib.Path,
        default=PROJECT_ROOT / f"stress-redirect-results-{ts}",
        help=f"Output directory for reports and profiles "
             f"(default: stress-redirect-results-<timestamp>)",
    )
    args = parser.parse_args()

    if not 0.0 < args.valid_ratio <= 1.0:
        print("ERROR: --valid-ratio must be in (0.0, 1.0]", file=sys.stderr)
        sys.exit(1)

    runner = StressRunner(
        interval=args.interval,
        concurrency=args.concurrency,
        prism_port=args.prism_port,
        output_dir=args.output_dir,
        valid_ratio=args.valid_ratio,
        path_count=args.path_count,
    )

    # Handle Ctrl-C gracefully during setup
    def _sig_handler(signum, frame):
        print("\nInterrupted during setup — cleaning up...")
        runner.teardown(collect_profiles=False)
        sys.exit(1)

    signal.signal(signal.SIGINT, _sig_handler)

    try:
        runner.setup()

        # Restore default SIGINT for stress phase (KeyboardInterrupt in run())
        signal.signal(signal.SIGINT, signal.SIG_DFL)

        metrics = runner.run()
        runner.report(metrics)
    except Exception as e:
        print(f"\nERROR: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        runner.teardown()


if __name__ == "__main__":
    main()
