// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/openana/prism/pkg/config"
	"github.com/openana/prism/pkg/index"
	"github.com/openana/prism/pkg/log"
	"github.com/openana/prism/pkg/mirrors"
	"github.com/openana/prism/pkg/router"
	"github.com/openana/prism/pkg/url"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.Config) (*Server, func(), error) {
	serverConfig, err := ProvideServerConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	routerConfig, err := ProvideRouterConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	loggerConfig, err := ProvideLoggerConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := log.NewLogger(loggerConfig)
	if err != nil {
		return nil, nil, err
	}
	accessLoggerConfig, err := ProvideAccessLoggerConfig(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	accessLogger, cleanup2, err := log.NewAccessLogger(accessLoggerConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	trieResolverConfig := ProvideTrieResolverConfig(cfg)
	trieResolver := url.NewTrieResolver(trieResolverConfig, logger)
	managerConfig, err := ProvideMirrorManagerConfig(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	manager, cleanup3, err := mirrors.NewManager(managerConfig, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cachedProviderConfig, err := ProvideCachedIndexProviderConfig(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cachedProvider, err := index.NewCachedProvider(cachedProviderConfig, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	routerRouter := router.NewRouter(routerConfig, logger, accessLogger, trieResolver, manager, cachedProvider)
	server := NewServer(serverConfig, routerRouter, logger)
	return server, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func ProvideServerConfig(cfg *config.Config) (ServerConfig, error) {
	return cfg.ToServer()
}

func ProvideRouterConfig(cfg *config.Config) (router.RouterConfig, error) {
	return cfg.HTTP.ToRouter()
}

func ProvideLoggerConfig(cfg *config.Config) (log.LoggerConfig, error) {
	return cfg.Log.ToLogger()
}

func ProvideAccessLoggerConfig(cfg *config.Config) (log.AccessLoggerConfig, error) {
	return cfg.AccessLog.ToLogger()
}

func ProvideTrieResolverConfig(cfg *config.Config) url.TrieResolverConfig {
	return cfg.ToTrieResolver()
}

func ProvideMirrorManagerConfig(cfg *config.Config) (mirrors.ManagerConfig, error) {
	return cfg.ToMirrorManager()
}

func ProvideCachedIndexProviderConfig(cfg *config.Config) (index.CachedProviderConfig, error) {
	return cfg.ToCachedProvider()
}
